export default function Home() {
  return (
    <div>
      <header>
        <h1>Next.js File Structure Explorer</h1>
        <p>A visual guide to every file and folder in a Next.js 15 project</p>
      </header>

      <main>
        <section>
          <h2>Root Level Configuration Files</h2>

          <div className="card">
            <div className="path">package.json</div>
            <h4>Package Manifest</h4>
            <p>
              Contains project metadata, scripts (dev, build, start, lint),
              runtime dependencies (next, react, react-dom), and devDependencies
              (typescript, type definitions, eslint).
            </p>
            <span className="tag">scripts</span>
            <span className="tag">dependencies</span>
            <span className="tag">devDependencies</span>
          </div>

          <div className="card">
            <div className="path">tsconfig.json</div>
            <h4>TypeScript Configuration</h4>
            <p>
              Configures the TypeScript compiler. Key options include strict mode
              for type safety, moduleResolution set to bundler for Next.js
              compatibility, jsx set to preserve, and path aliases via the paths
              option.
            </p>
            <span className="tag">strict</span>
            <span className="tag">paths</span>
            <span className="tag">moduleResolution</span>
          </div>

          <div className="card">
            <div className="path">next.config.ts</div>
            <h4>Next.js Configuration</h4>
            <p>
              The central configuration file for Next.js behavior. Supports image
              remote patterns, redirects, rewrites, custom headers, environment
              variables, webpack customization, and experimental features.
            </p>
            <span className="tag">images</span>
            <span className="tag">redirects</span>
            <span className="tag">webpack</span>
          </div>

          <div className="card">
            <div className="path">postcss.config.mjs</div>
            <h4>PostCSS Configuration</h4>
            <p>
              Configures PostCSS plugins. Primarily relevant when using Tailwind
              CSS (tailwindcss plugin) or other PostCSS-based tools like
              autoprefixer.
            </p>
            <span className="tag">tailwindcss</span>
            <span className="tag">autoprefixer</span>
          </div>

          <div className="card">
            <div className="path">eslint.config.mjs</div>
            <h4>ESLint Configuration</h4>
            <p>
              Linting configuration for code quality. Next.js provides a
              recommended base config that enforces best practices for React,
              accessibility, and performance.
            </p>
            <span className="tag">linting</span>
            <span className="tag">code quality</span>
          </div>

          <div className="card">
            <div className="path">next-env.d.ts</div>
            <h4>TypeScript Declarations</h4>
            <p>
              Auto-generated file that provides TypeScript with type information
              for Next.js globals and image imports. Do not edit this file
              manually.
            </p>
            <span className="tag">auto-generated</span>
            <span className="tag">do not edit</span>
          </div>

          <div className="card">
            <div className="path">.gitignore</div>
            <h4>Git Ignore</h4>
            <p>
              Specifies files and folders that Git should ignore. Includes
              node_modules, .next build output, environment files, and
              TypeScript build info.
            </p>
            <span className="tag">git</span>
            <span className="tag">ignore</span>
          </div>

          <div className="card">
            <div className="path">package-lock.json</div>
            <h4>Dependency Lock File</h4>
            <p>
              Auto-generated by npm. Locks the exact versions of every
              dependency and sub-dependency to ensure reproducible builds across
              environments.
            </p>
            <span className="tag">auto-generated</span>
            <span className="tag">npm</span>
          </div>

          <div className="card">
            <div className="path">README.md</div>
            <h4>Project Documentation</h4>
            <p>
              Markdown file for documenting the project. Generated with
              boilerplate content by create-next-app. Replace with your own
              project description.
            </p>
            <span className="tag">documentation</span>
          </div>
        </section>

        <section>
          <h2>Public Folder</h2>

          <div className="card">
            <div className="path">public/</div>
            <h4>Static Assets Directory</h4>
            <p>
              Serves static files directly at the root URL path. A file at
              public/logo.svg is accessible at /logo.svg. Use for images, fonts,
              robots.txt, sitemap.xml, and other static assets.
            </p>
            <span className="tag">static</span>
            <span className="tag">public assets</span>
          </div>
        </section>

        <section>
          <h2>.next Folder</h2>

          <div className="card">
            <div className="path">.next/</div>
            <h4>Build Output Directory</h4>
            <p>
              Auto-generated build output created when running dev, build, or
              start. Contains compiled JavaScript, optimized assets, and cached
              data. Always gitignored. Safe to delete -- Next.js regenerates it.
            </p>
            <span className="tag">auto-generated</span>
            <span className="tag">gitignored</span>
          </div>
        </section>

        <section>
          <h2>App Folder (App Router)</h2>

          <div className="card">
            <div className="path">app/favicon.ico</div>
            <h4>Browser Tab Icon</h4>
            <p>
              The icon displayed in the browser tab. Replace this file with
              your own favicon to brand your application.
            </p>
          </div>

          <div className="card">
            <div className="path">app/globals.css</div>
            <h4>Global Stylesheet</h4>
            <p>
              CSS styles that apply to the entire application. Imported by the
              root layout. Define base resets, font families, and global design
              tokens here.
            </p>
            <span className="tag">global styles</span>
          </div>

          <div className="card">
            <div className="path">app/layout.tsx</div>
            <h4>Root Layout</h4>
            <p>
              The outermost wrapper for all pages. Defines the HTML structure
              (html, body tags), metadata exports (title, description), and
              any persistent UI like navbars or footers. The children prop
              receives the currently active page component.
            </p>
            <span className="tag">layout</span>
            <span className="tag">metadata</span>
            <span className="tag">children</span>
          </div>

          <div className="card">
            <div className="path">app/page.tsx</div>
            <h4>Home Page Route</h4>
            <p>
              The main page component for the root route (/). In file-based
              routing, page.tsx is the only file that creates a publicly
              accessible URL. The component name is flexible; the filename
              determines the route.
            </p>
            <span className="tag">routing</span>
            <span className="tag">home page</span>
          </div>
        </section>

        <section>
          <h2>How Layout and Page Work Together</h2>

          <div className="card">
            <h4>The children Prop</h4>
            <p>
              In layout.tsx, the children prop represents the currently active
              route page. Everything rendered outside of {"{children}"} (navbar,
              footer) stays the same across all pages. When navigating from /
              to /about, only children changes -- the surrounding layout remains.
            </p>
          </div>

          <div className="card">
            <h4>Metadata API</h4>
            <p>
              Export a metadata object from layout.tsx to define default SEO
              properties (title, description, open graph). Individual pages can
              override these by exporting their own metadata.
            </p>
          </div>

          <div className="card">
            <h4>The next/image Component</h4>
            <p>
              Use Image from next/image for automatic image optimization. It
              supports lazy loading by default, responsive sizes, and WebP/AVIF
              conversion. Requires width and height for layout stability.
            </p>
          </div>
        </section>
      </main>

      <footer>
        <p>Generated by create-next-app -- File Structure Explorer</p>
      </footer>
    </div>
  );
}
